### ISSUE TITLE
Number of spline basis functions

### ISSUE THREAD

**Issue by robertdj** [sostock/BSplines.jl#27]
Hi 

Thank you for this package. I consider using it in another package, but there is a thing I don't understand -- from simple examples I expect to have fewer functions.

Consider the knot vector 

```julia
using BSplines
knots = [0; 0; 0; 1; 1; 1]
basis = BSplineBasis(1, knots)
```

Here, `length(basis)` returns 5 as expected and plotting the function look right. But when increasing the order I run into trouble

```julia
basis = BSplineBasis(2, knots)
```

Here, `length(basis)` returns 6, but I expect 4. Consider the output of `plot(basis)`

![basis2](https://user-images.githubusercontent.com/5703657/150678799-fa55e781-868c-4299-ad30-9e85ede46a88.png)

I would index the functions from 0 through 3. I expect the 0th and 3rd functions to be constantly 0. The 1st and 2nd should be the two straight lines. 
What are the rest?

This becomes a problem when constructing a `Spline` because it insists on having a larger `coeffs` vector than the number of basis functions I anticipate.

**Comment by hyrodium** [comment]
>Here, `length(basis)` returns 6, but I expect 4.

It seems the constructor `BSplineBasis` automatically inserts additional knots on the endpoints. (i.e. the knot vector will be converted from `[0,0,0,1,1,1]` to `[0,0,0,0,1,1,1,1]` for order 2 (polynomial degree 1). ) With these converted knot vector, number of B-spline functions is 6.

If you would like to have four B-spline functions with knots (0,1) and polynomial degree 1, the following script seems working fine here.
```julia
julia> basis = BSplineBasis(2, [0,0,1,1])
4-element BSplineBasis{Vector{Int64}}:
 order: 2
 breakpoints: [0, 0, 1, 1]

julia> length(basis)
4
```

**Comment by robertdj** [comment]
Thanks @hyrodium ! It makes sense that the constructor extends the knots based on the order.
